"""Idle-CPU verification for the batch/canvas-energy cuts to
`site/assets/portfolio.js`.

The mission was zero visual change, only a change in *when* the rAF loop
paints: idle while a tab is hidden, idle after the one owed frame once
reduced motion settles, resumed the instant either condition lifts. Two
behavioural claims and one visual claim, in that order:

1. Reduced motion idles the loop instead of re-rasterizing an identical
   frame every tick. `toDataURL()` equality is the observable -- two reads
   600ms apart are byte-identical once nothing new was drawn, and differ
   once painting resumes.
2. A hidden tab (`document.hidden` + a synthetic `visibilitychange`, the only
   way Playwright can simulate backgrounding) pauses the loop outright, and
   a visible one resumes it -- the same dataURL-equality technique.
3. Neither cut changed what a *visible, continuously-animated* page looks
   like anywhere outside the three canvases. Those regions are randomly
   seeded and perpetually in motion by design, so a live screenshot can
   never byte-match a captured one there; they are masked out of the compare
   and checked separately for "something is actually drawn" via luminance,
   so an idle canvas can never pass by going blank.

The baseline fixture (`tests/fixtures/portfolio_energy_baseline.png`) was
originally captured from the pre-edit file -- `git stash push --
site/assets/portfolio.js`, boot the server, screenshot, `git stash pop` -- at
the same route, viewport, dpr, and settle this file uses, so a regression
touching layout, colour, or copy anywhere outside the three canvases fails the
byte compare. It is not regenerated by this file: nothing here can see the
pre-edit source once the edit is committed, which is exactly why the image is
checked in instead.

Re-captured 2026-08-10 against the current build. The owner ruled a set of
deliberate visual changes (the header's motion toggle removed, the brand mark
enlarged, the `offset N` chips dropped from the experience rows, project
statuses corrected to `pre-alpha`), so the stored image no longer described the
page and every run failed on changes that were the point. Regenerating shifts
what this assertion means -- from "the canvas-energy batch changed nothing" to
"nothing outside the canvases changes from here without someone saying so" --
which is the guarantee worth keeping now that the batch is history.

Requires a built server binary (`cargo build`, run here if needed) and
Playwright/Chromium; both are skipped rather than failed when unavailable,
matching `tests/test_island.py`.
"""

import io
import os
import random
import shutil
import subprocess
import time
import urllib.error
import urllib.request
from collections.abc import Iterator
from pathlib import Path

import pytest

sync_api = pytest.importorskip("playwright.sync_api", reason="playwright is not installed")
from PIL import Image, ImageDraw  # noqa: E402  (Pillow is a hard project dependency)
from playwright.sync_api import Browser, Page, sync_playwright  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
SITE = REPO_ROOT / "site"
SERVER_BINARY = SITE / "target" / "debug" / "ui-servo-site"
BASELINE_PNG = REPO_ROOT / "tests" / "fixtures" / "portfolio_energy_baseline.png"

# Assigned to this unit for the parallel batch this work landed in, so its
# dev server never collides with a sibling worktree's. 8080 is a human's
# interactive session and must never be this port.
PORT = 8105

VIEWPORT = {"width": 1920, "height": 950}
DPR = 2
SETTLE_MS = 6000  # the margin/black-hole scenes are animated; give them room
BOOT_TIMEOUT_S = 30.0
ACTION_TIMEOUT_MS = 15_000

# Peak luminance (0-255) a canvas region reaches when it actually painted
# stars/glow. The bare page background alone (near-black #08090b) peaks
# under 20 in the same crop; real content spikes well past 100.
BLANK_LUMINANCE_MAX = 40

pytestmark = pytest.mark.playwright


@pytest.fixture(scope="module")
def base_url() -> Iterator[str]:
    """A real `cargo`-built server, launched directly (not via `cargo run`,
    which would leave the child holding the port when killed) -- the same
    approach `tests/test_island.py` uses, pinned to this unit's port instead
    of a free one.
    """
    if shutil.which("cargo") is None:
        pytest.skip("cargo is not installed")
    subprocess.run(["cargo", "build"], cwd=SITE, check=True)

    url = f"http://127.0.0.1:{PORT}"
    environment = os.environ | {"UI_SERVO_PORT": str(PORT)}
    environment.pop("UI_SERVO_DEV", None)
    server = subprocess.Popen(
        [str(SERVER_BINARY)],
        cwd=SITE,
        env=environment,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    try:
        deadline = time.monotonic() + BOOT_TIMEOUT_S
        while time.monotonic() < deadline:
            if server.poll() is not None:
                raise RuntimeError(f"server exited early with {server.returncode}")
            try:
                with urllib.request.urlopen(f"{url}/", timeout=1) as response:
                    if response.status == 200:
                        break
            except (urllib.error.URLError, TimeoutError, ConnectionError):
                time.sleep(0.1)
        else:
            raise RuntimeError(f"server never answered on {url}")
        yield url
    finally:
        server.terminate()
        try:
            server.wait(timeout=10)
        except subprocess.TimeoutExpired:
            server.kill()


@pytest.fixture(scope="module")
def browser() -> Iterator[Browser]:
    with sync_playwright() as playwright:
        try:
            instance = playwright.chromium.launch()
        except Exception as error:  # noqa: BLE001  # pragma: no cover - environment, not logic
            pytest.skip(f"chromium is not available: {error}")
        try:
            yield instance
        finally:
            instance.close()


def open_page(browser: Browser, *, reduced: bool) -> Page:
    """A fresh context/page at the golden-capture viewport and dpr, with the
    motion toggle pinned before any script runs.

    A fresh context, not a shared page: `pf-reduced` persists in
    `localStorage`, so it is the only reliable way to start a test from a
    known motion state rather than inheriting whatever a previous test left
    behind.
    """
    context = browser.new_context(viewport=VIEWPORT, device_scale_factor=DPR)
    value = "1" if reduced else "0"
    context.add_init_script(f"try {{ localStorage.setItem('pf-reduced', '{value}'); }} catch (e) {{}}")
    page = context.new_page()
    page.set_default_timeout(ACTION_TIMEOUT_MS)
    return page


def canvas_data_url(page: Page, canvas_id: str) -> str:
    return page.eval_on_selector(f"#{canvas_id}", "el => el.toDataURL()")


# --------------------------------------------------------------------------- #
# 1. Reduced motion idles the loop; un-reducing resumes it.
# --------------------------------------------------------------------------- #


def test_reduced_motion_idles_after_one_settled_frame(base_url: str, browser: Browser) -> None:
    """`#pf-canvas-l` is present and animated on every page (unlike `#pf-bh`,
    which needs `/projects/blackcell`), so the home page is enough to watch
    whether the loop idles.

    This used to click `#pf-motion` to flip the state mid-page. The owner
    removed that button (2026-08-10), so the transition it drove no longer
    exists in the product and testing it would test dead code. What still
    exists -- and is what a real visitor gets -- is the boot-time state, read
    from `prefers-reduced-motion` or the stored key. `open_page` pins that key
    before any script runs, so each state gets its own context.
    """
    still = open_page(browser, reduced=True)
    try:
        still.goto(f"{base_url}/", wait_until="domcontentloaded")
        still.wait_for_selector("#pf-canvas-l", state="attached")
        still.wait_for_timeout(500)  # the one owed frame renders and the loop settles
        still_a = canvas_data_url(still, "pf-canvas-l")
        still.wait_for_timeout(600)
        still_b = canvas_data_url(still, "pf-canvas-l")
        assert still_a == still_b, "reduced-motion loop kept re-rasterizing an unchanged frame"
    finally:
        still.context.close()

    moving = open_page(browser, reduced=False)
    try:
        moving.goto(f"{base_url}/", wait_until="domcontentloaded")
        moving.wait_for_selector("#pf-canvas-l", state="attached")
        moving.wait_for_timeout(300)
        moving_a = canvas_data_url(moving, "pf-canvas-l")
        moving.wait_for_timeout(600)
        moving_b = canvas_data_url(moving, "pf-canvas-l")
        assert moving_a != moving_b, "loop never painted a second frame with motion on"
    finally:
        moving.context.close()


# --------------------------------------------------------------------------- #
# 2. A hidden tab pauses the loop outright; a visible one resumes it.
# --------------------------------------------------------------------------- #

_HIDE = (
    "() => {"
    " Object.defineProperty(document, 'hidden', { get: () => true, configurable: true });"
    " document.dispatchEvent(new Event('visibilitychange'));"
    "}"
)
_SHOW = (
    "() => {"
    " Object.defineProperty(document, 'hidden', { get: () => false, configurable: true });"
    " document.dispatchEvent(new Event('visibilitychange'));"
    "}"
)


def test_hidden_tab_pauses_and_resumes_the_loop(base_url: str, browser: Browser) -> None:
    """Chromium lets a page script override `document.hidden` and fire a
    synthetic `visibilitychange`; Playwright has no API for an actual
    OS-level tab switch, so this is the standard way to simulate one.
    """
    page = open_page(browser, reduced=False)
    try:
        page.goto(f"{base_url}/", wait_until="domcontentloaded")
        page.wait_for_selector("#pf-canvas-l", state="attached")
        page.wait_for_timeout(300)

        page.evaluate(_HIDE)
        page.wait_for_timeout(150)
        paused_a = canvas_data_url(page, "pf-canvas-l")
        page.wait_for_timeout(600)
        paused_b = canvas_data_url(page, "pf-canvas-l")
        assert paused_a == paused_b, "loop kept drawing while document.hidden was true"

        page.evaluate(_SHOW)
        page.wait_for_timeout(150)
        resumed_a = canvas_data_url(page, "pf-canvas-l")
        page.wait_for_timeout(600)
        resumed_b = canvas_data_url(page, "pf-canvas-l")
        assert resumed_a != resumed_b, "loop did not resume once the tab became visible again"
    finally:
        page.context.close()


# --------------------------------------------------------------------------- #
# 3. Nothing outside the three canvases changed, and none of them went blank.
# --------------------------------------------------------------------------- #


def canvas_rects_px(page: Page) -> dict[str, tuple[float, float, float, float]]:
    """Device-pixel bounding boxes of the three canvas scenes, read once,
    right before the screenshot.

    They are `position:fixed`, so `getBoundingClientRect()` holds for the
    whole capture regardless of scroll or page height, and their geometry is
    CSS this unit never touches -- only their paint schedule changed.
    """
    rects = page.evaluate(
        "() => Object.fromEntries(['pf-canvas-l', 'pf-canvas-r', 'pf-bh'].map((id) => {"
        "  const el = document.getElementById(id);"
        "  const r = el.getBoundingClientRect();"
        "  return [id, [r.left, r.top, r.width, r.height]];"
        "}))"
    )
    return {name: tuple(v * DPR for v in box) for name, box in rects.items()}


def _box(rect: tuple[float, float, float, float], pad: float = 0) -> tuple[int, int, int, int]:
    x, y, w, h = rect
    return (int(x - pad), int(y - pad), int(x + w + pad), int(y + h + pad))


def _masked(image: Image.Image, boxes: list[tuple[int, int, int, int]]) -> Image.Image:
    out = image.copy()
    draw = ImageDraw.Draw(out)
    for box in boxes:
        draw.rectangle(box, fill=(0, 0, 0))
    return out


def _peak_luminance(image: Image.Image, box: tuple[int, int, int, int]) -> int:
    return image.crop(box).convert("L").getextrema()[1]


def test_visual_parity_outside_the_three_canvas_regions(base_url: str, browser: Browser) -> None:
    """`/projects/blackcell` carries all three canvas ids on one page and has
    no other auto-animating chrome (the typed-command caret and its blink
    live only on `/`), so it is the one route where a byte-for-byte compare
    of the unmasked page is meaningful.

    Reduced motion is forced on for this capture, matching how the stored
    baseline was taken, so nothing but the canvases -- which still paint
    their one settled frame under reduced motion -- could legitimately
    differ.
    """
    if not BASELINE_PNG.is_file():
        pytest.skip(f"no baseline fixture at {BASELINE_PNG}")

    page = open_page(browser, reduced=True)
    try:
        page.goto(f"{base_url}/projects/blackcell", wait_until="domcontentloaded")
        page.wait_for_selector("#pf-bh", state="attached")
        page.wait_for_timeout(SETTLE_MS)

        rects = canvas_rects_px(page)
        # A fixed seed, not a real source of entropy: pads each mask a few
        # pixels past the element's own box so no edge-antialiasing sliver
        # can leak into the byte compare, while staying reproducible run to
        # run.
        rng = random.Random(20260809)
        padded_boxes = [_box(rect, rng.randint(3, 10)) for rect in rects.values()]

        live_bytes = page.screenshot(full_page=True)
    finally:
        page.context.close()

    live = Image.open(io.BytesIO(live_bytes)).convert("RGB")
    baseline = Image.open(BASELINE_PNG).convert("RGB")
    assert live.size == baseline.size, (
        f"page geometry changed: baseline {baseline.size} vs live {live.size} -- "
        "this batch is only supposed to change WHEN canvases repaint, not layout"
    )

    assert _masked(live, padded_boxes).tobytes() == _masked(baseline, padded_boxes).tobytes(), (
        "a pixel outside the three canvas regions changed -- "
        "this batch is supposed to touch paint scheduling only"
    )

    for name, rect in rects.items():
        peak = _peak_luminance(live, _box(rect))
        assert peak > BLANK_LUMINANCE_MAX, (
            f"{name} looks blank (peak luminance {peak}) -- idle must never mean an empty canvas"
        )
